website/music/urls.py
from django.urls import  re_path
from . import views

app_name = 'music'

urlpatterns = [
    # /musis/
    re_path(r'^$', views.IndexView.as_view(), name='index'),

    re_path(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /musis/71/
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /musis/album_id/favourite/
    re_path(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

    # /music/album/add/
    re_path(r'album/add/$', views.AlbumCreate.as_view(), name='album_add'),

    # /music/album/2/
    re_path(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album_update'),

    # /music/album/delete /
    re_path(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album_delete'),
]

website/website/urls.py
from django.urls import  re_path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite= models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

website/music/views.py
from django.http import HttpResponse
from django.http import Http404
from django.template import  loader
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
     model = Album
     template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title' , 'genre' , 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title' , 'genre' , 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'


    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request,self.template_name, {'form': form})


    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user =  form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})





"""
def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk = album_id)
    return render(request, 'music/detail.html', {'album': album})
"""
def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return  render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

"""
def detail(request, album_id):
   try:
       album = Album.objects.get(pk=album_id)
   except Album.DoesNotExist:
       raise  Http404("Album does not exist")
   return render(request, 'music/detail.html', {'album': album})
"""
"""
def index(request):
    all_albums = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = {
        'all_albums': all_albums,
    }
    return HttpResponse(template.render(context,request))
"""
"""
def index(request):
    all_albums = Album.objects.all()
    html = ''
    for album in all_albums:
        url = '/music/' + str(album.id) + '/'
        html += '<a href="' + url + '">' + album.album_title + '</a><br>'
    return HttpResponse(html)
"""
"""
def detail(request, album_id):
    return HttpResponse("<h2>Details for Album id:" +str(album_id)+ "</h2>")

"""

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title%}Add a New Album{% endblock %}
{% block albums_active%}active{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MusicHall{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collepse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index'%}">MusicHall</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a a href="{% url 'music:index'%}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class=" nav navbar-nav navbar-right">
                <li class="">
                    <a a href="{% url 'music:album_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>


</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}
    <img src="{{ album.album_logo }}">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {% if error_message%}
        <p><strong>{{ error.message }}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id%}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
            <label for="song{{forloop.counter}}">
                {{song.song_title}}
                {% if song.is_favorite%}
                    <img style="width: 20px;" src="https://www.clipartmax.com/png/middle/37-370288_star-clip-art-tiny-star-clip-art.png"/>
                {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favorite">
    </form>

{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

        <h3>Here are all my albums:</h3>
        <ul>
            {% for album in object_list %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
             <form action="{% url 'music:album_delete' album.id %}" method="post" style="display: inline">
                 {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}">
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>
            {% endfor %}

        </ul>
{% endblock %}

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title%}Registration{% endblock %}
{% block albums_active%}active{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}